services:
  ros2_dev:
    build: .
    network_mode: bridge
    environment:
      - DISPLAY=:99
      - QT_QPA_PLATFORM=xcb
    volumes:
      - ./src:/root/ros2_ws/src
    stdin_open: true
    tty: true
    command: ["/root/ros2_ws/src/start_xvfb.sh", "bash"]
    ports:
      - "5900:5900"  # Map VNC port to host